[client]
showErrorDetails = true

[logger]
level = "error"

[server]
headless = true
runOnSave = true
port = 8501
enableXsrfProtection = false

[theme]
primaryColor = "#f59e0b"
backgroundColor = "#faf7f1"
secondaryBackgroundColor = "#ffffff"
textColor = "#1c1917"
font = "sans serif"
